### ISSUE TITLE
feat #9 - transaction

### ISSUE THREAD

**Issue by Shin-sangwon** [SSAFY-enjoytrip/backend#16]
### 🗄️ 종류

issue 종류를 선택하세요

- [ ] Code Review
- [ ] New Feature
- [ ] Remove Feature
- [ ] Change Logic
- [ ] Bug Fix
- [ ] Setup
## 🔍Description

> 거래 내역 도메인 생성하기

## 📝Todo

- [x] 마일리지 추가
- [x] 예약 시 예약금 감소 로직
- [ ] 예약 확정 시 잔금 결제
- [x] 이틀 전 예약 취소 시 전액 환불, 그 뒤에 예약 취소 시 예약금 환불 불가
